spring:
  profiles:
    active:
    - core
    - home
  application:
    name: bootz-security-demo
  messages:
    basename: i18n/messages
  session:
    timeout: 30s
    redis:
      cleanup-cron: 0 0/1 * * * ?
  http:
    encoding:
      force: true
server:
  port: 8060
  tomcat:
    uri-encoding: UTF-8
  error:
    path: /html/error/404.html
logging:
  level:
    root: info
    top.bootz: debug
bootz:
  security:
    session:
      loginPage: /html/login.html
      loginType: JSON
    code:
      imageCode:
        width: 100
        height: 32
        length: 5
        expire-in: 60