spring:
  profiles:
    active:
    - home
  application:
    name: bootz-security-demo
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: false
    properties:
      hibernate.dialect.storage_engine: innodb
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      hibernate.cache.provider_class: org.hibernate.cache.NoCacheProvider
      hibernate.format_sql: false
      hibernate.ejb.entitymanager_factory_name: entityManagerFactory
  messages:
    basename: i18n/messages
  session:
    timeout: 2h
    redis:
      cleanup-cron: 0 0/1 * * * ?
  http:
    encoding:
      force: true
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    root: info
    top.bootz: debug
bootz:
  security:
    session:
      login-type: JSON
      login-page: /pages/login.html
      sign-up-url: /pages/sign-up.html
    cors:
      allowed-methods:
      - GET
      - HEAD
      - POST
      - PUT
      - DELETE
      - OPTIONS
      allowed-origins:
      - bootz.top
      - bootz.cn
      - pinzhi365.com
      max-age: 7200
    code:
      imageCode:
        width: 100
        height: 32
        length: 5
        expire-in: 120
    social:
      filter-processes-url: /login
      qq:
        app-id: 101504242
        app-secret: 5520dc9cfbf426cce6280a1495c5c2d8