spring:
  profiles:
    active:
    - core
    - home
  application:
    name: bootz-security-demo
  messages:
    basename: i18n/messages
  session:
    timeout: 2h
    redis:
      cleanup-cron: 0 0 0/1 * * ?
  http:
    encoding:
      force: true
server:
  port: 8060
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    root: info
    top.bootz: debug
bootz:
  security:
    session:
      loginPage: /html/login.html
      loginType: JSON