spring:
  profiles:
    active:
    - home
  application:
    name: bootz-user
  cache:
    type: redis
    cache-names:
    - userCache
    - authCache
    - resourceCache
    redis:
      key-prefix: 'usercenter:'
      time-to-live:
        seconds: 86400
  datasource:
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: false
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      use-global-data-source-stat: true
      filters: stat,wall,slf4j
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: true
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            selelct-allow: true
        slf4j:
          enabled: true
          data-source-log-enabled: true
          connection-log-enabled: true
          connection-log-error-enabled: true
          statement-log-enabled: true
          statement-log-error-enabled: true
      web-stat-filter:
        enabled: true
        exclusions: '*.js, *.gif, *.jpg, *.png, *.css, *.ico, /druid/*'
        principal-session-name: username
        url-pattern: /api/v1/*
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: 1990912
        reset-enable: false
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    converters:
      preferred-json-mapper: null
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
  jpa:
    database: mysql
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect.storage_engine: innodb
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      hibernate.cache.provider_class: org.hibernate.cache.NoCacheProvider
      hibernate.show_sql: false
      hibernate.format_sql: false
      hibernate.ejb.entitymanager_factory_name: entityManagerFactory
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
  messages:
    basename: i18n/messages,i18n/messages
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  task:
    pool:
      custom:
        thread-name-prefix: Bootz-Executor-
        core-pool-size: 5
        max-pool-size: 20
        keep-alive-seconds: 120
        queue-capacity: 10
server:
  port: 6080
  tomcat:
    accesslog:
      enabled: true
      request-attributes-enabled: true
    min-spare-threads: 25
    max-threads: 800
    uri-encoding: UTF-8
  connection-timeout:
    seconds: 60
id-generator:
  work-id: 0
  data-center-id: 0