spring:
  application:
    name: BOOTZ-USER
datasource:
    url: jdbc:mysql://192.168.199.106:3306/orion?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=round&rewriteBatchedStatements=true
    username: root 
    password: 1990912
    initialSize: 5
    minIdle: 5
    maxActive: 10
    maxWait: 30000
    timeBetweenEvictionRunsMillis: 
    